### ISSUE TITLE
Create pool & Payoff types

### ISSUE THREAD

**Issue by juliankrispel** [divaprotocol/diva-monorepo#200]
## Context

We'd like to simplify the UX for configuring contingent pools by introducing payoff types that the user can select and thereby reducing the number of inputs required.

## Stories

- [ ] Payoff type selection
- [ ] Binary pool template
- [ ] Linear pool template
