### ISSUE TITLE
Trade page epic

### ISSUE THREAD

**Issue by Walodja1987** [divaprotocol/diva-monorepo#532]
## Stories
- [x] #569
- [x] #527 
- [x] #505 
- [x] #528 
- [x] #529 
- [ ] #530 (code refactoring; low prio for now)
- [ ] #524 (code refactoring; low prio for now)
- [ ] #487 (@cryptoHersh has already started working on it)
- [x] #388 
- [ ] #525 
- [ ] #448 
- [ ] #502 
- [x] #471 
- [ ] #306 
- [x] #531
- [x] #520 
- [ ] #539 
- [ ] #541 
- [x] #542
